spring:
  data:
    mongodb:
      uri: mongodb+srv://covid19soln1:${spring.data.mongodb.password}@grsdev7-qorpx.mongodb.net/covid19soln1?retryWrites=true&w=majority

log:
  level:
    org:
      mongodb:
        driver:
          client: DEBUG
          cluster: DEBUG